### ISSUE TITLE
forward from init controller

### ISSUE THREAD

**Issue by famonsei** [laruence/yaf#163]
Hy,

It's possible to execute un forward from init function in controller ?

my example :
```
class RestController extends Controller
{
	private $action;
	private $controller;
	/**
	 * Init for each action
	 */
	public function init()
	{
		// disable render for all action
		Yaf\Dispatcher::getInstance()->disableView();

		// check existing controller
		$controllerAllow = array('repository');
		$this->controller = $this->getRequest()->getActionName();
		if (!in_array($this->controller, $controllerAllow))
			Response::sendJsonException(EvaluationError::$codes[1120]);

		// check method used
		$methodAllow = array('GET', 'POST', 'PUT', 'DELETE');
		$this->action = in_array($this->getRequest()->getMethod(), $methodAllow) ? strtolower($this->getRequest()->getMethod()) : 'get';
		
		// redirect according to method
		// $this->forward(strtolower($this->getModuleName()), $controller, $action);
	}
}
```
error 500 with no log if I remove comment this line
```
// $this->forward(strtolower($this->getModuleName()), $controller, $action);
```

Thx

**Comment by nly** [comment]
May be the action you wanna foward and the init method are in the same controller or extends the controller, this will cause a dead loop. Because each action will execute the init method.

    public function init()
    {
        echo 'init';
        //$this->forward('index','test'); //init() and test() are in the same controller
        //$this->forward('login','index'); // another controller and action, this works well
    }

    public function indexAction(){
        echo 'index';
        //$this->forward('index','test'); // if put forward here, you will see "init" twice
    }

    public function testAction()
    {
        echo 'test';  // will execute init() as well
    }

Like : init->test->init->test->init->test ...........

But,finaly, there is bug here, if only set action like `$this->forward('test');` , this will trigger a error `The max dispatch nesting %ld was reached`, but `$this->forward('index', 'test');` , NOT .

@laruence  鸟哥瞅瞅呗。

**Comment by laruence** [comment]
@famonsei @nly it should be fixed, sorry for late response,  I missed this message at all :<

**Comment by nly** [comment]
@laruence 嘿嘿
